services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      DB_USER: "app_user"
      DB_PASSWORD: "secret"
      DB_HOST: "mariadb"
      DB_PORT: "3306"
      DB_NAME: "app_db"
    ports:
      - "8080:8080"

  mariadb:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: "rootpass"
      MARIADB_DATABASE: "app_db"
      MARIADB_USER: "app_user"
      MARIADB_PASSWORD: "secret"
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  prometheus:
    image: prom/prometheus:v2.54.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"


volumes:
  mariadb_data:
